project_at_v1_1/blogs/urls.py
from django.conf.urls import patterns, url
from blogs import views
urlpatterns = patterns('', 
	url(r'^$', views.blog, name="blog_post"),
	)

project_at_v1_1/project_at_v1_1/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
     url(r'^blogs/', include('blogs.urls', namespace='blog')),
    url(r'^', include('user_register.urls', namespace='registration')),
    url(r'^', include('student.urls', namespace='students')),
    url(r'^', include('tutor.urls', namespace='tutors')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_at_v1_1/student/urls.py
from django.conf.urls import patterns, url
from student import views
urlpatterns = patterns('', 
	url(r'^personality/$', views.personality, name="personality"),
	url(r'^dashboard/$', views.dashboard, name="dashboard"),
	url(r'^cal/$', views.calendar, name="cal"),
	url(r'^calevent/$', views.calEvent, name="events"),
	url(r'^planlist/$', views.planList, name="planlists"),
	url(r'^profile/$', views.studentProfile, name="studentprofile"),
	url(r'^qbank/ds/$', views.questionBankds, name="questionbank"),
	url(r'^qbank/ps/$', views.questionBankps, name="questionbank"),
	url(r'^qbank/rc/$', views.questionBankrc, name="questionbank"),
	url(r'^qbank/cr/$', views.questionBankcr, name="questionbank"),
	url(r'^qbank/sc/$', views.questionBanksc, name="questionbank"),
	url(r'^test/$', views.cat, name="cat"),
	url(r'^stocks/$', views.stock, name="highstock"),
	url(r'^stocks2/$', views.stock2, name="highstock"),
	url(r'^gd/$', views.genieDialogue, name="dialects"),
	url(r'^sd/$', views.studentDialogue, name="dialects"),
	url(r'^tutors/$', views.tutors, name="tutors"),
	url(r'^dashboard/tutor/(?P<username>\w+)$', views.tutorProfile, name="tutorprofiles"),
	url(r'^mailsent/$', views.mailSent, name="mails"),
	url(r'^logged-out/$', views.signout, name="signout"),
	)

project_at_v1_1/tutor/urls.py
from django.conf.urls import patterns, url
from tutor import views
urlpatterns = patterns('', 
	url(r'^t-dashboard/$', views.t_dashboard, name="tdash"),
	)

project_at_v1_1/user_register/urls.py
from django.conf.urls import patterns, url
from user_register import views
urlpatterns = patterns('', 
	url(r'^$', views.home, name="home"),
	url(r'^welcome/$', views.welcome, name="welcome"),
	url(r'^welcome/choose/$', views.wc, name="wchoose"),
	)

project_at_v1_1/user_register/models.py
from django.db import models
import datetime
import time
import uuid
import hashlib
from django.utils import timezone
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from student.storage import OverwriteStorage
# class User_reg(models.Model):
# 	name = models.CharField(max_length=50)
# 	email = models.CharField(max_length=50)
# 	password = models.CharField(max_length=50)
# 	utype = models.CharField(max_length=2)
# 	#created_at = models.DateField(default=date.today)
# 	class Meta:
# 		abstract = True
class RegistrationManager(BaseUserManager):
    def create_user(self, email, username, utype="NA", zone=0, is_active=True, created_at=timezone.now(), password=None, g_signup=False, key="", expiry=timezone.now()):
        """
        Creates and saves a User with the given email, name, utype, timezone, active and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        time = timezone.now()
        time = time.strftime('%m%d%Y-%H%M%S%f')
        hashed_time = hashlib.sha256(time).hexdigest()
        a_key = str(uuid.uuid4())
        a_key = ''.join(a_key.split('-')) + hashed_time
        user = self.model(
            email=self.normalize_email(email),
            username=username,
            utype=utype,
            is_active=is_active,
            created_at = created_at,
            zone = zone,
            g_signup = g_signup,
            key = a_key,
            expiry = expiry
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

class Registration(AbstractBaseUser):
	username = models.CharField(max_length=50)
	email = models.CharField(max_length=50)
	#password = models.CharField(max_length=50)
	is_active = models.BooleanField()
	utype = models.CharField(max_length=2)
	created_at = models.DateTimeField()
	zone = models.IntegerField()
	g_signup = models.BooleanField()
	key = models.TextField()
	expiry = models.DateTimeField()
	photo = models.FileField(upload_to='photos', storage=OverwriteStorage())

	objects = RegistrationManager()
	USERNAME_FIELD = 'username'
	REQUIRED_FIELDS = ['utype', 'is_active', 'created_at', 'zone', 'g_signup', 'key', 'expiry']

	def __unicode__(self):
		return self.username

# class StudentRegistration(User_reg):
# 	def __unicode__(self):
# 		return self.name

# class TutorRegistration(User_reg):
# 	def __unicode__(self):
# 		return self.name

# class ParentRegistration(User_reg):
# 	def __unicode__(self):
# 		return self.name
# Create your models here.

project_at_v1_1/user_register/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from user_register.models import Registration
from datetime import datetime
from django.utils import timezone
import uuid
import hashlib
from django.contrib import messages
from datetime import timedelta
from django.views.decorators.csrf import requires_csrf_token
from django.contrib.auth import logout
#from django.contrib.auth.models import AbstractBaseUser
from django.core.mail import send_mail
#from user_register.models import User

# Create your views here.
@requires_csrf_token
def home(request):
	if request.method == 'POST':
		if 'resetemail' in request.POST:
			if Registration.objects.filter(email=request.POST['resetemail']).filter(is_active=True).exists():
				a = Registration.objects.get(email=request.POST['resetemail'])
				name = ''
				email_to = a.email
				if a.g_signup:
					name = a.username
				else:
					s = a.social_auth.first()
					if s.provider == "facebook":
						name = a.username
					if s.provider == "google-oauth2":
						name = s.extra_data['first_name']
					if s.provider == "linkedin":
						name = s.extra_data['first_name']
				reset_key = 'http://localhost:5000/?rst='+a.key
				a.expiry = timezone.now() + timedelta(minutes=5)
				a.save()
				msg = """Hi %s,\n\nWe recieved information that you want to reset your password.
				\n\nIf this information was not provided by you. Please ignore and delete this message.\n\n
				click on the link below to reset your password %s.""" %(name, reset_key)
				send_mail("Reset Password", msg,"info@learnaptive.com", [email_to])
				messages.success(request, "Reset email has been sent to your email.")
				return redirect('/')
			else:
				messages.error(request, "This email id has not registered with us. Register with us now.")
				return redirect('/')

		elif 'resetpass' and 'hidemail' in request.POST:
			a = Registration.objects.get(email=request.POST['hidemail'])
			a.set_password(request.POST['resetpass'])
			a.save()
			request.session['SSID'] = a.id
			return redirect("/")
		else:
			logout(request)
			return redirect('/')

	else:
		if 'rst' in request.GET:
			if request.GET['rst'] == '':
				error = 'No link found. Try again'
				context = {'error': error}
				return render(request, 'user_register/home.html', context)
			a = Registration.objects.filter(key=request.GET['rst']) # What if length > 1?
			if a:
				if datetime.now() > a[0].expiry:
					#error = 'This link has expired. Reset again'
					time = timezone.now()
					time = time.strftime('%m%d%Y-%H%M%S%f')
					hashed_time = hashlib.sha256(time).hexdigest()
					a_key = str(uuid.uuid4())
					a[0].key = ''.join(a_key.split('-')) + hashed_time #Ques: Can there be collision?
					a[0].save()
					messages.error(request, "This link has expired. Reset again")
					return redirect('/')
				# a[0].is_active = True
				time = timezone.now()
				time = time.strftime('%m%d%Y-%H%M%S%f')
				hashed_time = hashlib.sha256(time).hexdigest()
				a_key = str(uuid.uuid4())
				a[0].key = ''.join(a_key.split('-')) + hashed_time #Ques: Can there be collision?
				email = a[0].email
				a[0].save()
				# request.session['SSID'] = a[0].id
				context = {'email': email}
				return render(request, 'user_register/home.html', context)
			else:
				messages.error(request, "This link has expired.")
				return redirect('/')

		if 'confirm' in request.GET:
			if request.GET['confirm'] == '':
				error = 'No link found. Try again'
				context = {'error': error}
				return render(request, 'user_register/home.html', context)
			a = Registration.objects.filter(key=request.GET['confirm']) # If collision then use 'filter' in place of 'get'
			if a:
				if a[0].is_active:
					# error = 'This link has expired. User already activated'
					# context = {'error': error}
					# return render(request, 'user_register/home.html', context)
					messages.error(request, "This link has expired. User already activated")
					return redirect('/')

				if datetime.now() > a[0].expiry:
					error = 'This link has expired. Register again'
					time = timezone.now()
					time = time.strftime('%m%d%Y-%H%M%S%f')
					hashed_time = hashlib.sha256(time).hexdigest()
					a_key = str(uuid.uuid4())
					a[0].key = ''.join(a_key.split('-')) + hashed_time #Ques: Can there be collision?
					a[0].save()
					messages.error(request, "This link has expired. Register again")
					# context = {'error': error}
					# return render(request, 'user_register/home.html', context)
					return redirect('/')

				a[0].is_active = True
				time = timezone.now()
				time = time.strftime('%m%d%Y-%H%M%S%f')
				hashed_time = hashlib.sha256(time).hexdigest()
				a_key = str(uuid.uuid4())
				a[0].key = ''.join(a_key.split('-')) + hashed_time #Ques: Can there be collision?
				a[0].save()
				request.session['SSID'] = a[0].id
				return redirect('/')
			else:
				messages.error(request, "This link has expired.")
					# context = {'error': error}
					# return render(request, 'user_register/home.html', context)
				return redirect('/')
				# error = 'This link has expired.'
				# context = {'error': error}
				# return render(request, 'user_register/home.html', context)

		if "SSID" in request.session:
			ssid = request.session['SSID']
			a = Registration.objects.get(id=ssid)
			if a.utype == 'ST':
				return redirect('/dashboard/')
			if a.utype == 'TU':
				return redirect('/t-dashboard/')

		return render(request, 'user_register/home.html')

def welcome(request):
	"""this function is called after user signs up or logs in."""
	if request.method == 'POST':
		if "reg_username" in request.POST: #Sign up takes to one time welcome page
			if request.POST['reg_username'] and request.POST['email'] and request.POST['reg_pwd'] and request.POST['option'] and request.POST['zone']:
				if Registration.objects.filter(email=request.POST['email']).filter(is_active=True).exists(): #--TODO: when database entry is zero
					error = 'This email is there with us already. Try signing up using different email'
					context = {'error': error}
					return render(request, 'user_register/home.html', context)
				else:
					#save user as inactive and send confirmation mail
					zone = int(request.POST['zone'])
					d = timezone.now() + timedelta(minutes=-(zone))
					exp = timezone.now() + timedelta(minutes=5)
					c = Registration.objects.create_user(username=request.POST['reg_username'], email=request.POST['email'], password=request.POST['reg_pwd'], utype=request.POST['option'], is_active=False, created_at=d, zone=zone, g_signup=True, key='', expiry=exp)
					c.save()
					email_to = request.POST['email']
					activation_key = 'http://localhost:5000/?confirm='+c.key
					msg = """Hi %s,\n\nThank you for registering with us.\n\nFollowing are the username
					and password that you gave us.\n\nIf any of the feilds do not match then it is not
					you. Ignore this message if it is not you.\n\n\nusername: %s\n\npassword: %s
					\n\n\nclick on the link below to activate your account %s.""" %(request.POST['reg_username'],request.POST['email'],request.POST['reg_pwd'],activation_key)
					send_mail("Confirm your Email to get started", msg, "learnaptive@learnaptive.com", [email_to])
					#a = Registration.objects.get(email=request.POST['email'])
					#r = a.created_at
					category = request.POST['option']
					if category == 'ST':
						category = 'Student'
					if category == 'TU':
						category = 'Tutor'
					if category == 'PA':
						category = 'Parent'
					#request.session['SSID'] = c.id
					#when user sign up show them the welcome.html page
					context = {'username': request.POST['reg_username'], 'category': category, 'user': c}
					return render(request, 'user_register/welcome.html', context)

		elif "useremail" in request.POST: #Log in directly to dashboard
			if request.POST['useremail'] and request.POST['pwd']:
				if Registration.objects.filter(email=request.POST['useremail']).filter(is_active=True).exists():
					c = Registration.objects.filter(email=request.POST['useremail']).get(is_active=True)
					if not c.check_password(request.POST['pwd']):
						messages.error(request, "Your password do not match. Try again")
						return redirect('/')
					if c.utype == 'ST':
						request.session['SSID'] = c.id
						return redirect('/dashboard/')
					if c.utype == 'TU':
						request.session['SSID'] = c.id
						return redirect('/t-dashboard/')
				elif Registration.objects.filter(email=request.POST['useremail']).filter(is_active=False).exists():
					messages.error(request, "Sorry, This account is not verified. Go to your mail and activate it now.")
					return redirect('/')
				else:
					messages.error(request, "This email id has not registered with us. Register with us now.")
					return redirect('/')

		else:
			messages.error(request, "Server error. Please wait sometimes")
			return redirect('/')


	else:
		if "SSID" in request.session:
			ssid = request.session['SSID']
			a = Registration.objects.get(id=ssid)
			if a.utype == 'ST':
				return redirect('/dashboard/')
			if a.utype == 'TU':
				return redirect('/t-dashboard/')
		if request.user.is_anonymous(): # if SSID not present and user is anonymous
			return redirect('/')


def wc(request):
	"""Get request for successful redirection of social authentication"""
	if 'SSID' in request.session: # If SSID is present
		ssid = request.session['SSID']
		a = Registration.objects.get(id=ssid)
		if a.utype == 'ST':
			return redirect('/dashboard/')
		if a.utype == 'TU':
			return redirect('/t-dashboard/')
	if request.user.is_anonymous(): # if SSID not present and user is anonymous
		return redirect('/')
	if request.method == 'POST': #updating utype value which was set to "NA"
		if 'option' in request.POST:
			utype = request.POST['option']
			pwd = request.POST['pwd']
			zone = request.POST['tz']
			a = Registration.objects.get(id=request.user.id)
			a.utype = utype
			a.zone = zone

project_at_v1_1/user_register/templates/user_register/wc.html
{% load staticfiles %}
<head><title>EdGenie | Welcome and Choose</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

  <link href="{% static 'user_register/bootstrap/css/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'user_register/bootstrap/css/bootstrap-responsive.css' %}" rel="stylesheet">
  <link href="{% static 'user_register/stylesheets/font-awesome.css' %}" rel="stylesheet">
  <link href="{% static 'user_register/stylesheets/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'user_register/stylesheets/signup.css' %}" rel="stylesheet">
  <link href="{% static 'user_register/stylesheets/clingify.css' %}" rel="stylesheet">
  <link href="{% static 'user_register/stylesheets/some.css' %}" rel="stylesheet">

</head>
<body style="background-color: #dddddd;">
<div style="background-color: #ffffff;">
<div class="container" style="background-color: #ffffff; padding-bottom: 30px;">
    <div class="form-group" style="padding-top:20px;">
    <div class="col-md-2">
    </div>
    <div class="col-md-8" align="center">
    <div class="col-md-12 col-xs-12">
            <img src="{% static 'user_register/images/learnaptive blue.png' %}" class="img-responsive center-block" style="height: 56.69px; width: 200px;">
        </div>
        <div><i style="color: #808080; font-size: 10px;"> The scientific method for teaching science!</i></div>
    </div>

    <div class="col-md-2">
    </div>

    </div>
    </div>
    </div>
    <div style="padding-top: 70px; padding-bottom: 70px;">

    <div class="col-md-3"></div>
<div class="col-md-6" style="background-color: #ffffff;">

    <div style="padding-top: 50px; padding-bottom: 70px;">
    <div class="form-group" style="padding-top:20px;">
    <div class="col-md-2">
    </div>

<div class="col-md-8" style="padding-bottom: 40px;" align="center">
{% if category != 'NA' %}
  <div style="padding-bottom: 30px; font-size: 24px; color: #666666;">Welcome to EdGenie, {{username.title}} You are a {{ category }}</div><div style="padding-bottom: 30px; color: #666666;"> lets get started with a quick tour to help you explore us better </div>
{% else %}
<form method="post">{% csrf_token %}
  <div style="padding-bottom: 30px; font-size: 24px; color: #666666;">Welcome to EdGenie, {{username.title}}</div>
  <div class="col-md-12" style="padding-bottom: 15px;">
  <div class="col-md-12">Choose your category:
    <select class="form-control" style="height: 50px;" name="option" autocomplete="off">
                              <option value="ST">I am a student</option>
                              <option value="TU">I am a tutor</option>
                              <option value="PA">I am a parent</option>
                            </select>
  </div>
  <div class="col-md-12">
    <input type="password" class="form-control" name="pwd" style="height: 50px;" placeholder="a memorable password">
  </div>
  <input type="text" class="zone" name="tz" style="display: none;">
  </div>
  <div class="form-group">
  <div class="col-md-12">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <button class="btn btn-primary form-control" style="background-color: #006699;">submit</button>
    </div>
    <div class="col-md-4"></div>
    </div>
    </div>
   </form>
{% endif %}
{% if category == 'Student' %}
    <form action="{% url 'students:dashboard' %}">
    <div class="form-group">
    <div class="col-md-4"></div>
    <div class="col-md-4">
    	<button class="btn btn-primary form-control" style="background-color: #006699;">start</button>
    </div>
    <div class="col-md-3"></div>
    </div>
    <div class="em"></div>
    </form>
{% endif %}
{% if category == 'Tutor' %}
    <form action="{% url 'tutors:tdash' %}">
    <div class="form-group">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <button class="btn btn-primary form-control" style="background-color: #006699;">start</button>
    </div>
    <div class="col-md-3"></div>
    </div>
    <div class="em"></div>
    </form>
{% endif %}
</div>
</div>

</div>

</div>
</div>
  <script src="{% static 'user_register/bootstrap/js/jquery.min.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/bootstrap.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/jquery-ui.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/jquery-ui.min.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/jquery.flip.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/jquery.flip.min.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/jquery.clingify.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/demo.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/some.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/custom.js' %}"></script>
<script type="text/javascript">
  var d = new Date()
  $('.zone').val(d.getTimezoneOffset());
</script>
</body>

project_at_v1_1/user_register/templates/user_register/welcome.html
{% load staticfiles %}
<head><title>EdGenie | Welcome</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

  <link href="{% static 'user_register/bootstrap/css/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'user_register/bootstrap/css/bootstrap-responsive.css' %}" rel="stylesheet">
  <link href="{% static 'user_register/stylesheets/font-awesome.css' %}" rel="stylesheet">
  <link href="{% static 'user_register/stylesheets/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'user_register/stylesheets/signup.css' %}" rel="stylesheet">
  <link href="{% static 'user_register/stylesheets/clingify.css' %}" rel="stylesheet">
  <link href="{% static 'user_register/stylesheets/some.css' %}" rel="stylesheet">

</head>
<body style="background-color: #dddddd;">
<div style="background-color: #ffffff;">
<div class="container" style="background-color: #ffffff; padding-bottom: 30px;">
    <div class="form-group" style="padding-top:20px;">
    <div class="col-md-2">
    </div>
    <div class="col-md-8" align="center">
    <div class="col-md-12 col-xs-12">
            <img src="{% static 'user_register/images/learnaptive blue.png' %}" class="img-responsive center-block" style="height: 56.69px; width: 200px;">
        </div>
        <div><i style="color: #808080; font-size: 10px;"> The scientific method for teaching science!</i></div>
    </div>

    <div class="col-md-2">
    </div>

    </div>
    </div>
    </div>
    <div style="padding-top: 70px; padding-bottom: 70px;">

    <div class="col-md-3"></div>
<div class="col-md-6" style="background-color: #ffffff;">

    <div style="padding-top: 50px; padding-bottom: 70px;">
    <div class="form-group" style="padding-top:20px;">
    <div class="col-md-2">
    </div>

<div class="col-md-8" style="padding-bottom: 40px;" align="center">
<div style="padding-bottom: 30px; font-size: 24px; color: #666666;">Welcome to EdGenie, {{username.title}} You are a {{ category }}</div>
{% if not user.is_active %}
      <div class="alert alert-success" role="alert">
        A confirmation mail has been sent to the email given by you. To proceed further please confirm
        your account.<a href="/" class="alert-link">Click here to go back</a>
      </div>
    {% endif %}

{% if user.is_active %}
  <div style="padding-bottom: 30px; color: #666666;"> lets get started with a quick tour to help you explore us better </div>
  {% if category == 'Student' %}
      <form action="{% url 'students:dashboard' %}">
      <div class="form-group">
      <div class="col-md-4"></div>
      <div class="col-md-4">
      	<button class="btn btn-primary form-control" style="background-color: #006699;">start</button>
      </div>
      <div class="col-md-3"></div>
      </div>
      <div class="em"></div>
      </form>
  {% endif %}
  {% if category == 'Tutor' %}
      <form action="{% url 'tutors:tdash' %}">
      <div class="form-group">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <button class="btn btn-primary form-control" style="background-color: #006699;">start</button>
      </div>
      <div class="col-md-3"></div>
      </div>
      <div class="em"></div>
      </form>
  {% endif %}
{% endif %}
</div>
</div>

</div>

</div>
</div>
  <script src="{% static 'user_register/bootstrap/js/jquery.min.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/bootstrap.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/jquery-ui.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/jquery-ui.min.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/jquery.flip.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/jquery.flip.min.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/jquery.clingify.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/demo.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/some.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/custom.js' %}"></script>

</body>