project_at_v1_1/blogs/urls.py
from django.conf.urls import patterns, url
from blogs import views
urlpatterns = patterns('', 
	url(r'^$', views.blog, name="blog_post"),
	)

project_at_v1_1/project_at_v1_1/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
     url(r'^blogs/', include('blogs.urls', namespace='blog')),
    url(r'^', include('user_register.urls', namespace='registration')),
    url(r'^', include('student.urls', namespace='students')),
    url(r'^', include('tutor.urls', namespace='tutors')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_at_v1_1/tutor/urls.py
from django.conf.urls import patterns, url
from tutor import views
urlpatterns = patterns('', 
	url(r'^t-dashboard/$', views.t_dashboard, name="tdash"),
	)

project_at_v1_1/user_register/urls.py
from django.conf.urls import patterns, url
from user_register import views
urlpatterns = patterns('', 
	url(r'^$', views.home, name="home"),
	url(r'^welcome/$', views.welcome, name="welcome"),
	url(r'^welcome/choose/$', views.wc, name="wchoose"),
	)

project_at_v1_1/tutor/models.py
from django.db import models

# Create your models here.

project_at_v1_1/tutor/views.py
from django.shortcuts import render
from django.http import HttpResponse
def t_dashboard(request):
	if request.method == 'GET':
		# if 'dashem' in request.POST:
		# 	dash = request.POST['dashem']
		# 	context = {'days': dash}
			return render(request, 'tutor/t_dash.html')
	else:
		return HttpResponse("page not found")
# Create your views here.

project_at_v1_1/tutor/templates/tutor/t_dash.html
{% load staticfiles %}
<head><title>EdGenie | Dashboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

  <link href="{% static 'user_register/bootstrap/css/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'user_register/bootstrap/css/bootstrap-tour.css' %}" rel="stylesheet">
  <link href="{% static 'user_register/bootstrap/css/bootstrap-tour.min.css' %}" rel="stylesheet">
  <link href="{% static 'user_register/bootstrap/css/bootstrap-responsive.css' %}" rel="stylesheet">
  <link href="{% static 'user_register/stylesheets/font-awesome.css' %}" rel="stylesheet">
  <link href="{% static 'user_register/stylesheets/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'user_register/stylesheets/signup.css' %}" rel="stylesheet">
  <link href="{% static 'user_register/stylesheets/some.css' %}" rel="stylesheet">

</head>
</head>
<body>
<div>
<div class="container" style="background-color: #ffffff; padding-bottom: 20px;">
    <div class="form-group" style="padding-top:20px;">
    <div class="col-xs-10 col-md-10">

            <img src="{% static 'user_register/images/learnaptive blue.png' %}" class="img-responsive" style="height: 56.69px; width: 200px;">

        <div><i style="color: #808080; font-size: 9px;"> The scientific method for teaching science!</i></div>

    </div>
    <div class="col-xs-2 col-md-2" style="padding-top:15px; color: #666666;" align="center"><i class="fa fa-user fa-2x dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown"></i> {{username.title}}
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
    <li role="presentation"><a role="menuitem" tabindex="-1" href="/profile/">Your Profile</a></li>
    <li role="presentation" class="divider"></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#" class="signout">Logout</a></li>
  </ul>


</div>
<div style="display: none;">
<form method="post" action="{% url 'registration:home' %}" class="logoutform">{% csrf_token %}
</form>
</div>
    </div>
    </div>

    </div>
<div>
<div class="navbar navbar-default" style="background-color: #666666; border-bottom: 1px solid white;">
<div class="navbar-inner">
      <div class="navbar-header pull-left">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-3">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar" style="background-color: #FFFFFF;"></span>
          <span class="icon-bar" style="background-color: #FFFFFF;"></span>
          <span class="icon-bar" style="background-color: #FFFFFF;"></span>
        </button>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-3">
        <ul class="nav nav-tabs" id="demo">
          <li class="nav_zero" id="nav0"><a href="#home" style="color: #FFFFFF;" data-toggle="tab" id="anc1"><i class="fa fa-home fa-1x"></i> Home</a></li>
          <li class="nav_zero" id="nav1"><a href="#profile" style="color: #FFFFFF;" data-toggle="tab">Profile</a></li>
          <li class="nav_zero" id="nav2"><a href="#statistics" style="color: #FFFFFF;" data-toggle="tab">Statistics</a></li>
        </ul>
      </div>
</div>
</div>
</div>

<div class="tab-content">
  <div class="tab-pane active" id="home">
  <div class="container" style="color: #666666;">
<div align="center" style="padding-bottom: 20px;">
  <p><h2>Welcome to EdGenie, Username</h2></p>
  <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
</div>
<div class="col-md-4" style="padding-bottom: 20px; padding-top: 0px; padding-left: 0px; padding-right: 0px;">
  <div class="col-md-12" style="padding: 5px;">
  <div class="col-md-12" align="center" style="background: #006699; color: #fff; line-height: 4;">
Profile Reach
  </div>
  <div class="col-md-12" style="padding-bottom: 100px; border: 1px solid gray;">
  123 students<br>
  5.7% from last week
  </div>
  </div>
  </div>
<div class="col-md-4" style="padding-bottom: 20px; padding-top: 0px; padding-left: 0px; padding-right: 0px;">
  <div class="col-md-12" style="padding: 5px;">
  <div class="col-md-12" align="center" style="background: #006699; color: #fff; line-height: 4;">
Engagements
  </div>
  <div class="col-md-12" style="padding-bottom: 100px; border: 1px solid gray;">
  123 students<br>
  5.7% from last week
  </div>
  </div>
</div>
<div class="col-md-4" style="padding-bottom: 20px; padding-top: 0px; padding-left: 0px; padding-right: 0px;">
  <div class="col-md-12" style="padding: 5px;">
  <div class="col-md-12" align="center" style="background: #006699; color: #fff; line-height: 4;">
Response Rate
  </div>
  <div class="col-md-12" style="padding-bottom: 100px; border: 1px solid gray;">
  123 students<br>
  5.7% from last week
  </div>
  </div>
</div>

<div class="col-md-4" align="center" style="padding-bottom: 20px; padding-top: 5px; padding-left: 5px; padding-right: 5px;">
<div class="col-md-12" style="background: #CCCCCC; border: 1px solid gray; padding: 10px;">
  <p>Get verified by EdGenie</p>
  <p>we will conduct a standard background check to improve your capability</p>
  <p><h2>FREE</h2></p>
  <button class="btn btn-primary">get verified</button>
  </div>
</div>
<div class="col-md-4" align="center" style="padding-bottom: 20px; padding-top: 5px; padding-left: 5px; padding-right: 5px;">
  <div class="col-md-12" style="background: #CCCCCC; border: 1px solid gray; padding: 10px;">
  <p>Let the Genie test you</p>
  <p>Genie will test your skills and expertise to increase the trust of your students</p>
  <p><h2>FREE</h2></p>
  <button class="btn btn-primary">take the test</button>
  </div>
</div>
<div class="col-md-4" style="padding-bottom: 20px; padding-top: 5px; padding-left: 5px; padding-right: 5px;">
  <div class="col-md-12" style="border: 1px solid gray; padding: 10px;">
  <p>Complete your profile:<br><div class="progress">
  <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 45%">
    <span class="sr-only">45% Complete</span>
  </div>
</div></p>
  <p>about me<br>about me<br>about me<br>about me<br>about me<br></p>
  </div>
</div>
</div>
</div>
<div class="tab-pane" id="profile" style="padding-top: 25px;">
<div class="container" style="padding-bottom: 20px;">
<div class="col-md-4" style="padding: 0px; border: 1px solid gray;">
<div class="col-md-12" style="padding-top: 15px; padding-bottom: 25px; border-bottom: 1px dashed gray;">
  <div class="media">
        <a class="pull-left" href="#" style="pointer-events: none;">
        <img class="media-object" src="#" alt="some picture here">
       </a>
        <div class="media-body" style="padding-left: 20px;">
        <p class="media-heading" align="center">Josh Atlas</p>
       <button class="btn btn-default form-control" style="background-color: #666666; color: #fff;">edit profile</button>
       </div>
        </div>
<div align="center" style="padding-top: 20px;">Average tutor rating:</div>
</div>
<div class="col-md-12" style="padding-top: 15px; padding-bottom: 25px; border-bottom: 1px dashed gray;">
<div><span style="font-size: 30px; color: #006699;"><b>73%</b></span> response rate</div>
<div style="font-size: 12px;">Responded to: 230 students</div>
<div style="font-size: 12px;">Response time: within 2 hours</div>
</div>
<div class="col-md-12" style="padding-top: 15px; padding-bottom: 25px; border-bottom: 1px dashed gray;">
<div style="padding-bottom: 10px;">About me</div>
<div style="font-size: 12px;">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut.
</div>
</div>
<div class="col-md-12" style="padding-top: 15px; padding-bottom: 25px; border-bottom: 1px dashed gray;">
<div style="padding-bottom: 10px;">Personal Information</div>
<div class="col-md-6" style="font-size: 12px;">Gender:</div>
<div class="col-md-6" style="font-size: 12px;">Male</div>
<div class="col-md-6" style="font-size: 12px;">Birthday:</div>
<div class="col-md-6" style="font-size: 12px;">October 2, 1990</div>
<div class="col-md-6" style="font-size: 12px;">Phone Number:</div>
<div class="col-md-6" style="font-size: 12px;">1234567890</div>
<div class="col-md-6" style="font-size: 12px;">Location:</div>
<div class="col-md-6" style="font-size: 12px;">San Francisco</div>
<div class="col-md-4" style="font-size: 12px;">Email ID:</div>
<div class="col-md-8" style="font-size: 12px;" align="center">chaitanya.srivastav123456789<wbr>@gmail.com</div>
</div>
<div class="col-md-12" style="padding-top: 15px; padding-bottom: 15px; border-bottom: 1px dashed gray;">
<div style="padding-bottom: 15px;">Pricing and details</div>
<div style="font-size: 12px;">$150 per hour on 1-on-1 sessions</div>
<div style="font-size: 12px; padding-bottom: 15px;">$110 per hour for group sessions</div>
<div style="font-size: 10px;">*Travel charges will be added separately</div>
<div style="font-size: 10px; padding-bottom: 40px;">*I also conduct group classes at my home</div>
</div>
</div>

<div class="col-md-8">
<div class="col-md-12" style="padding-right: 0px; padding-top: 0px; padding-left: 0px; padding-bottom: 20px;">
<div class="col-md-12" style="border: 1px solid gray; padding-bottom: 100px;">
  <div><span style="font-size: 30px; color: #006699;"><b>720</b></span> SAT score</div>
  </div>
  </div>
<div class="col-md-12" style="padding-right: 0px; padding-top: 0px; padding-left: 0px; padding-bottom: 20px;">
<div class="col-md-6" align="center" style="padding-top: 5px; padding-left: 5px; padding-right: 5px;">
<div class="col-md-12" style="background: #CCCCCC; border: 1px solid gray; padding: 10px;">
  <p>Get verified by EdGenie</p>
  <p>we will conduct a standard background check to improve your capability</p>
  <p><h2>FREE</h2></p>
  <button class="btn btn-primary">get verified</button>
  </div>
</div>
<div class="col-md-6" align="center" style="padding-top: 5px; padding-left: 5px; padding-right: 5px;">
  <div class="col-md-12" style="background: #CCCCCC; border: 1px solid gray; padding: 10px;">
  <p>Let the Genie test you</p>
  <p>Genie will test your skills and expertise to increase the trust of your students</p>
  <p><h2>FREE</h2></p>
  <button class="btn btn-primary">take the test</button>
  </div>
</div>
  </div>
<div class="col-md-12" style="padding-right: 0px; padding-top: 0px; padding-left: 0px; padding-bottom: 20px;">
<div class="col-md-12" style="border: 1px solid gray;">
  <div style="padding-top: 15px; padding-bottom: 15px;">Qualifications and achievements</div>
  <p style="padding-bottom: 25px;">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
  labore et</p>
  <p style="padding-bottom: 25px;">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
  labore et</p>
  <p style="padding-bottom: 25px;">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
  labore et</p>
  </div>
  </div>
<div class="col-md-12" style="padding-right: 0px; padding-top: 0px; padding-left: 0px; padding-bottom: 20px;">
<div class="col-md-12" style="border: 1px solid gray; padding-bottom: 20px;">
<div class="pull-right" style="padding-top: 15px;"><a href="#recommendmodal">Recommend</a></div>
  <div style="padding-top: 15px;">14 Recommendations</div>
  <div class="media">
        <a class="pull-left" href="#" style="pointer-events: none;">
        <img class="media-object" src="#" alt="picture here">
       </a>
        <div class="media-body" style="padding-left: 20px;">
       <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</div>
       </div>
        </div>
        <div class="media">
        <a class="pull-left" href="#" style="pointer-events: none;">
        <img class="media-object" src="#" alt="some picture">
       </a>
        <div class="media-body" style="padding-left: 20px;">
        <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</div>
       </div>
        </div>
  </div>
  </div>

</div>
</div>
</div>

  <div class="tab-pane" id="statistics">ghgvhjg gbhgvhjgh jgbhgvhg ghjghjghj</div>
</div>
<script src="{% static 'user_register/bootstrap/js/jquery.min.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/bootstrap.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/bootstrap-tour.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/bootstrap-tour.min.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/jquery-ui.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/jquery-ui.min.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/jquery.flip.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/jquery.flip.min.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/some.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/custom.js' %}"></script>
<script>
//window.localStorage.clear();
$('.nav_zero').navWithArrow();
$(document).reloadStay();
  </script>

<script type="text/javascript">
  window.setTimeout(function(){$(document).siteTour()}, 700);
</script>
<script type="text/javascript">
  $('.dropdown-toggle').dropdown();
  </script>
  <script type="text/javascript">
  $('.signout').click(function(){
    $('.logoutform').submit();
  });
</script>

</body>