project_at_v1_1/blogs/urls.py
from django.conf.urls import patterns, url
from blogs import views
urlpatterns = patterns('', 
	url(r'^$', views.blog, name="blog_post"),
	)

project_at_v1_1/project_at_v1_1/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
     url(r'^blogs/', include('blogs.urls', namespace='blog')),
    url(r'^', include('user_register.urls', namespace='registration')),
    url(r'^', include('student.urls', namespace='students')),
    url(r'^', include('tutor.urls', namespace='tutors')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_at_v1_1/student/urls.py
from django.conf.urls import patterns, url
from student import views
urlpatterns = patterns('', 
	url(r'^personality/$', views.personality, name="personality"),
	url(r'^dashboard/$', views.dashboard, name="dashboard"),
	url(r'^cal/$', views.calendar, name="cal"),
	url(r'^calevent/$', views.calEvent, name="events"),
	url(r'^planlist/$', views.planList, name="planlists"),
	url(r'^profile/$', views.studentProfile, name="studentprofile"),
	url(r'^qbank/ds/$', views.questionBankds, name="questionbank"),
	url(r'^qbank/ps/$', views.questionBankps, name="questionbank"),
	url(r'^qbank/rc/$', views.questionBankrc, name="questionbank"),
	url(r'^qbank/cr/$', views.questionBankcr, name="questionbank"),
	url(r'^qbank/sc/$', views.questionBanksc, name="questionbank"),
	url(r'^test/$', views.cat, name="cat"),
	url(r'^stocks/$', views.stock, name="highstock"),
	url(r'^stocks2/$', views.stock2, name="highstock"),
	url(r'^gd/$', views.genieDialogue, name="dialects"),
	url(r'^sd/$', views.studentDialogue, name="dialects"),
	url(r'^tutors/$', views.tutors, name="tutors"),
	url(r'^dashboard/tutor/(?P<username>\w+)$', views.tutorProfile, name="tutorprofiles"),
	url(r'^mailsent/$', views.mailSent, name="mails"),
	url(r'^logged-out/$', views.signout, name="signout"),
	)

project_at_v1_1/tutor/urls.py
from django.conf.urls import patterns, url
from tutor import views
urlpatterns = patterns('', 
	url(r'^t-dashboard/$', views.t_dashboard, name="tdash"),
	)

project_at_v1_1/student/models.py
from django.db import models
from datetime import datetime
from djangotoolbox.fields import ListField
class Timeline(models.Model):
	created_at = models.DateField()
	l_mins = models.IntegerField()
	l_num = models.IntegerField()
	attempted = models.IntegerField()
	subtimeline = ListField()
# Create your models here.

project_at_v1_1/tutor/models.py
from django.db import models

# Create your models here.

project_at_v1_1/student/forms.py
from django import forms
class DocumentForm(forms.Form):
	docfile = forms.FileField(
	label='Personalize your account'
	)

project_at_v1_1/student/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.utils import timezone
from datetime import date, datetime, timedelta
from django.contrib.auth import logout
from scripts.sat.codes.genie_loop import Loop
from django.core.mail import send_mail
from user_register.models import Registration
from student.models import Timeline
from student.forms import DocumentForm
import random
def dashboard(request):
	if request.method == 'GET':
		name = ''
		if 'SSID' in request.session:
			ssid = request.session['SSID']
			n = Registration.objects.get(id=ssid)
			if n.g_signup:
				name = n.username
			else:
				s = n.social_auth.first()
				if s.provider == "facebook":
					name = n.username
				if s.provider == "google-oauth2":
					name = s.extra_data['first_name']
				if s.provider == "linkedin":
					name = s.extra_data['first_name']
			zone = -(n.zone)
			c = datetime.now()
			c = c + timedelta(minutes=zone)
			time = Timeline.objects.filter(created_at=c.date()).order_by('created_at')
			timeline = Timeline.objects.filter(created_at__lt=c.date()).order_by('created_at')
			# firstname = n.social_auth.get(provider="facebook")
			# fname = firstname.extra_data['first_name']
		else:
			return redirect('/')
		context = {'name': name, 'n': n, 'timeline': timeline, 'time': time}
		return render(request, 'student/dashboard.html', context)
	# else:
	# 	return HttpResponse("Page not found")

def calendar(request):

	return render(request, 'student/calendar.html')

def personality(request):
	if request.method == 'POST':
		return render(request, 'student/personality.html')

	else:
		return HttpResponse("Page not found")

def calEvent(request):
	if request.is_ajax():
		return render(request, 'student/cal-event.html')

	else:
		return HttpResponse("Page not found")

def planList(request):
	if request.is_ajax():
		return render(request, 'student/plan-list.html')

	else:
		return HttpResponse("Page not found")

def tutors(request):
	if request.is_ajax():
		return render(request, 'student/tutors.html')


def tutorProfile(request, username):
	return render(request, 'student/tutor-profile.html')

def mailSent(request):
	if request.is_ajax():
		if request.method == "GET":
			if 'm' in request.GET:
				c = request.GET['m']
				email_to = 'chaitanya.srivastav@gmail.com'
				send_mail("Hi Josh", c,"somestudent@learnaptive.com", [email_to])
				return render(request, 'student/mail-sent.html')


student = {}
def genieDialogue(request):
	global student
	# if request.is_ajax():
	# 	if request.method == 'POST':
	# 		if 'uid' in request.POST:
	# 			context = {"question": 'hello', 'sol': 'bar'}
	# 			return render(request, 'student/genie.html', context)
	if 'uid' in request.POST:
		key = request.POST['uid']
		if not student.get(key):
			student[key] = {}
			student[key]['sol'] = ''
			student[key]['loop'] = Loop() #argument is hardcoded
		# else:
		# 	student[key]['loop'].set_ans(1)
		if request.is_ajax():
			if "resume_session" in request.POST:
				context = {'question': student[key]['curr_qn'], 'sol': student[key]['sol']}
				return render(request, 'student/genie.html', context)

			opt = []
			tp = 'MC1' #ye change hoga
			txt1 = ''
			if "answer" in request.POST:
	 			ans = request.POST['answer']
	 			if ans == "tutor": #when user clicks 'message', 'tutor' string is sent to views
	 				msg = request.POST['msg']
	 				email_to = 'chaitanya.srivastav@gmail.com'
					send_mail("Hi Josh", msg,"somestudent@learnaptive.com", [email_to])
	 				txt1 = """<p>Josh will respond you, as soon as he is online</p>
			 				<p>Lets move on to next question</p>"""
	 			else:
		 		 	ans = int(ans) + 1
					result = student[key]['loop'].set_ans(ans)
					student[key]['sol'] = result.get('sol', '')
					# sol = student[key]['sol']
					tutp = result.get('tutor', False)
					if tutp:
						txt = "Hello, my name is Josh. How can I help you?"
						student[key]['opt'] = ['-textarea-']
						student[key]['tp'] = "TUT"
						context = {'question': txt, 'sol': student[key]['sol']}
						return render(request, 'student/genie.html', context)
				# if sol:
				# 	context = {'solution': sol}
				# 	return render(request, 'student/genie.html', context)
			qn = student[key]['loop'].get_qn()
			if not qn:
				txt = 'loop over'
			else:
				choice = lambda xs: random.choice(xs)+' ' if xs else ''
				txt,opt,inter = qn['text'], qn['options'], choice(qn.get('interjects', []))
				if 'type' in qn.keys():
					tp = qn['type']
				else:
					tp = 'MC1'
				txt = txt1 + inter + txt
			 	opt = [str(opt[str(i+1)]) for i in range(len(opt))]
				#opt = ['a', 'b', 'c']
			#type of question to be checked later
			student[key]['curr_qn'] = txt
			student[key]['opt'] = opt
			student[key]['tp'] = tp
			context = {'question': student[key]['curr_qn'], 'sol': student[key]['sol']}
			return render(request, 'student/genie.html', context)

def studentDialogue(request):
	if 'uid' in request.POST:
		key = request.POST['uid']
	 	if request.is_ajax():
	 		opname = student[key]['opt']
	 		textstring = ''
			context = {'arr': opname, 's': textstring, 'type': student[key]['tp']}
	 		return render(request, 'student/student-d.html', context)

# def genieDialogue(request):
# 	if request.is_ajax():
# 		if "answer" in request.GET:
# 			context = {'chosen': request.GET["answer"]}
# 			return render(request, 'student/genie.html', context)
# 		elif 'tnumber' in request.GET:
# 			abc = []
# 			num = int(request.GET['tnumber'])
# 			for i in range(0,num):
# 				if 'option'+str(i) in request.GET:
# 					abc.append(int(request.GET['option'+str(i)]))
# 			context= {'abc': abc}
# 			return render(request, 'student/genie.html', context)
# 		else:
# 			return render(request, 'student/genie.html' )

# 	else:
# 		return HttpResponse("Page not found")

# def studentDialogue(request):
# 	if request.is_ajax():
# 		opname = ['A. a', 'B. b','C. c','D. d','E. e','F. f']
# 		textstring = 'this is -TX- and it helps us in submitting. -tx- great!'
# 		context = {'arr': opname, 's': textstring, 'type': 'btn'}
# 		return render(request, 'student/student-d.html', context)

# 	else:
# 		return HttpResponse("Page not found")

def studentProfile(request):
	name = ''
	email = ''
	gender = ''
	fullname = ''
	if 'SSID' in request.session:
		ssid = request.session['SSID']
		n = Registration.objects.get(id=ssid)
		if n.g_signup:
			name = n.username
			email = n.email
		else:
			s = n.social_auth.first()
			if s.provider == "facebook":
				name = n.username
				email = n.email
				gender = s.extra_data['gender']
				fullname = s.extra_data['full_name']
			if s.provider == "google-oauth2":
				name = s.extra_data['first_name']
				email = n.email
				gender = s.extra_data['gender']
				fullname = s.extra_data['first_name']+' '+s.extra_data['last_name']
			if s.provider == "linkedin":
				name = s.extra_data['first_name']
				email = n.email
				gender = s.extra_data['gender']
				fullname = s.extra_data['first_name']+' '+s.extra_data['last_name']
		# form = DocumentForm()
		if request.method == 'POST':
			form = DocumentForm(request.POST, request.FILES)
			if form.is_valid():
				n.photo = request.FILES['docfile']
				n.save()
		else:
			form = DocumentForm()
	else:
		return redirect('/')
	context = {'name': name, 'email': email, 'gender': gender, 'fullname': fullname, 'form': form, 'n': n}
	return render(request, 'student/student-profile.html', context)

def questionBankds(request):
	context = {'qtype': request.GET['dataSuff']}
	return render(request, 'student/qbank.html', context)

def questionBankps(request):
	context = {'qtype': request.GET['probSol']}
	return render(request, 'student/qbank.html', context)

def questionBankrc(request):
	context = {'qtype': request.GET['readComp']}
	return render(request, 'student/qbank.html', context)

def questionBankcr(request):
	context = {'qtype': request.GET['critReas']}
	return render(request, 'student/qbank.html', context)

def questionBanksc(request):
	context = {'qtype': request.GET['senCorr']}
	return render(request, 'student/qbank.html', context)

loop = None
def cat(request):
	global loop
	n = 5
	if request.method == "POST":
		if "examdate" in request.POST:
			if request.POST["examdate"]:
				if not test:
					test = Test()
				qn_text = test.get_qn()
				if qn_text == None:
					return render(request, 'student/student-profile.html')
				exam = request.POST['timeweekday']
				context = {"question": qn_text, "exam": exam}
				return render(request, 'student/test.html', context)
			else:
				return HttpResponse("Please provide exam date")

		if "choice" in request.POST:
			if request.POST['choice']:
				ans1 = request.POST['choice']
				ans = int(ans1)
				test.set_ans(ans)
				qn_text = test.get_qn() #if loop whether qn_text == None, then return HttpResponse "Test Over" with B values
				if qn_text == None:
					return render(request, 'student/test-result.html')
				context = {"question": qn_text, "answer": ans}
				return render(request, 'student/test.html', context)

		elif "skip" in request.POST:
			ans = 0
			test.set_ans(ans)
			qn_text = test.get_qn() #if loop whether qn_text == None, then return HttpResponse "Test Over" with B values
			if qn_text == None:
				return render(request, 'student/test-result.html')
			context = {"question": qn_text, "answer": ans}
			return render(request, 'student/test.html', context)

		else:
			#Student has hit the quit button
			test.quit_test()
			return render(request, 'student/test-result.html')

	else:
		return HttpResponse("Page not found")

def stock(request):
	if request.is_ajax():
		return render(request, 'student/high.json')
	else:
		return HttpResponse("Page not found")

def stock2(request):
	if request.is_ajax():
		return render(request, 'student/high2.json')
	else:
		return HttpResponse("Page not found")

def signout(request):
	logout(request)
	return render(request, 'user_register/home.html')
# Create your views here.

project_at_v1_1/tutor/views.py
from django.shortcuts import render
from django.http import HttpResponse
def t_dashboard(request):
	if request.method == 'GET':
		# if 'dashem' in request.POST:
		# 	dash = request.POST['dashem']
		# 	context = {'days': dash}
			return render(request, 'tutor/t_dash.html')
	else:
		return HttpResponse("page not found")
# Create your views here.

project_at_v1_1/student/templates/student/cal-event.html
<p>ajax call successfully worked!!!</p>

project_at_v1_1/student/templates/student/calendar.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Adaptube | Study Plan</title>
    <link href="{% static 'user_register/bootstrap/css/bootstrap.css' %}" rel="stylesheet" media="screen">
    <link href="{% static 'user_register/bootstrap/css/bootstrap-theme.min.css' %}" rel="stylesheet" media="screen">
     <link href="{% static 'user_register/stylesheets/calendar.css' %}" rel="stylesheet">
</head>
<body>
<div class="container">
<div class="page-header">

        <div class="pull-right form-inline">
            <div class="btn-group">
                <button class="btn btn-primary" data-calendar-nav="prev"><< Prev</button>
                <button class="btn btn-default" data-calendar-nav="today">Today</button>
                <button class="btn btn-primary" data-calendar-nav="next">Next >></button>
            </div>
            <div class="btn-group">
                <button class="btn btn-warning" data-calendar-view="year">Year</button>
                <button class="btn btn-warning active" data-calendar-view="month">Month</button>
                <button class="btn btn-warning" data-calendar-view="week">Week</button>
                <button class="btn btn-warning" data-calendar-view="day">Day</button>
            </div>
        </div>

        <h3></h3>
        
    </div>
<div id="calendar">
            </div>
<label class="checkbox pull-right">
                    <input type="checkbox" value="#events-modal" id="events-in-modal"> Open events in modal window
                </label>

                <div class="modal fade" id="events-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3 class="modal-title">Event</h3>
                </div>
                <div class="modal-body" style="height: 400px">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    
</div>
    <script src="{% static 'user_register/bootstrap/js/jquery.min.js' %}"></script>
    <script src="{% static 'bs3-calendar/components/underscore/underscore-min.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/bootstrap.js' %}"></script>
  <script src="{% static 'user_register/bootstrap/js/bootstrap.min.js' %}"></script>
  
    
    <script src="{% static 'bs3-calendar/js/calendar.js' %}"></script>
    <script src="{% static 'bs3-calendar/components/jstimezonedetect/jstz.min.js' %}"></script>
    

    <script type="text/javascript">
        var calendar = $("#calendar").calendar(
            {
                tmpl_path: "/static/bs3-calendar/tmpls/",
                view: 'week',
                events_source: '/static/bs3-calendar/events.json',
                onAfterEventsLoad: function(events) {
            if(!events) {
                return;
            }
            var list = $('#eventlist');
            list.html('');

            $.each(events, function(key, val) {
                $(document.createElement('li'))
                    .html('<a href="' + val.url + '">' + val.title + '</a>')
                    .appendTo(list);
            });
        },
                onAfterViewLoad: function(view) {
                    $('.page-header h3').text(this.getTitle());
                    $('.btn-group button').removeClass('active');
                    $('button[data-calendar-view="' + view + '"]').addClass('active');
            },
                classes: {
                    months: {
                    general: 'label'
                        }
                    }
            }); 

    $('.btn-group button[data-calendar-nav]').each(function() {
        var $this = $(this);
        $this.click(function() {
            calendar.navigate($this.data('calendar-nav'));
        });
    });

    $('.btn-group button[data-calendar-view]').each(function() {
        var $this = $(this);
        $this.click(function() {
            calendar.view($this.data('calendar-view'));
        });
    });

    $('#first_day').change(function(){
        var value = $(this).val();
        value = value.length ? parseInt(value) : null;
        calendar.setOptions({first_day: value});
        calendar.view();
    });

    $('#language').change(function(){
        calendar.setLanguage($(this).val());
        calendar.view();
    });

    $('#events-in-modal').change(function(){
        var val = $(this).is(':checked') ? $(this).val() : null;
        calendar.setOptions({modal: val});
    });
    $('#events-modal .modal-header, #events-modal .modal-footer').click(function(e){
        //e.preventDefault();
        //e.stopPropagation();
    });        
    </script>

</body>
</html>

project_at_v1_1/student/templates/student/genie.html
<html>
<head>
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']], processEscapes: true}
});

</script>
<script type="text/javascript"
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>
</head>
<body>
<div class="geniedialogue" style="line-height: 2; text-align: justify;">
    <p>{{sol|safe}}</p>
    <p>{{question|safe}}</p>
<!-- {{abc}} {{chosen}} --></div>
<script type="text/x-mathjax-config">

</script>
</body>
</html>

project_at_v1_1/student/templates/student/mail-sent.html
<div align="center"><p>your message has been sent to Josh</p></div>

project_at_v1_1/student/templates/student/personality.html
{% load staticfiles %}
<head><title>EdGenie | Basic Info</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

  <link href="{% static 'student/bootstrap/css/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'student/bootstrap/css/bootstrap-responsive.css' %}" rel="stylesheet">
  <link href="{% static 'student/stylesheets/font-awesome.css' %}" rel="stylesheet">
  <link href="{% static 'student/stylesheets/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'student/stylesheets/signup.css' %}" rel="stylesheet">
  <link href="{% static 'student/stylesheets/dashboard.css' %}" rel="stylesheet">
  <link href="{% static 'student/stylesheets/collapse.css' %}" rel="stylesheet">
  <link href="{% static 'student/stylesheets/calendar.css' %}" rel="stylesheet">
  <link href="{% static 'student/stylesheets/datepicker.css' %}" rel="stylesheet">

</head>
<body>
<div>
<div class="container" style="background-color: #ffffff; padding-bottom: 20px;">
    <div class="form-group" style="padding-top:20px;">
    <div class="col-xs-10 col-md-10">
            <img src="{% static 'user_register/images/learnaptive blue.png' %}" class="img-responsive" style="height: 56.69px; width: 200px;">

        <div><i style="color: #808080; font-size: 9px;"> The scientific method for teaching science!</i></div>

    </div>
    <div class="col-xs-2 col-md-2" style="padding-top:15px; color: #666666;" align="center"><i class="fa fa-user fa-2x dropdown-toggle" id="dropdownMenu1" data-toggle="dropdown"></i> {{username.title}}
  <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
    <li role="presentation"><a role="menuitem" tabindex="-1" href="/profile/">Your Profile</a></li>
    <li role="presentation" class="divider"></li>
    <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Logout</a></li>
  </ul>


</div>
    </div>
    </div>

    </div>
    <div>
        	<div class="form-group" align="center">
    		<div class="col-md-12" style="background-color: #006699; padding-bottom: 25px; padding-top: 25px;">
    			<p style="font-size: 20px; color: #fff;">Let's build your personalised training program</p>
    			<div class="form-group">
    			<div class="col-md-4"></div>
    			<div class="col-md-4" style="margin: 25px 0 0;">
    			<div style="float: left; color: #fff;">Self assess</div>
    			<div style="float: right; color: #fff;">Verbal</div>
    			<div style="color: #fff; padding-right: 10px;">Quantitative</div>
    			<div class="parent"><div class="child"></div></div>
    			</div>
    			<div class="col-md-4"></div>
    			</div>
    		</div>
    	</div>
    </div>

    <div class="form-group">
    <div class="col-md-4"></div>
    <div class="col-md-4" style="padding-top: 30px;">
    <form method="post" action="/test/">{% csrf_token %}
    <p>When is your exam scheduled for?</p>
    <div class="form-group has-feedback">
  <label class="control-label sr-only" for="inputDate">Input with Date</label>
  <input type="text" class="form-control" id="inputDate" name="examdate">
  <span class="glyphicon glyphicon-calendar form-control-feedback"></span>
</div>
    <div style="padding-top: 30px;">
    <p>At an average how many hours a day will you be able to study?</p>
    <div class="form-group">
    <div class="col-sm-12 col-md-12" style="padding-bottom: 30px;">
    <div class="col-md-4 col-sm-4">

    </div>

    <div class="col-md-4 col-sm-4">
    <div class="input-group">
    <input type="text" name="timeweekend" class="form-control" style="height: 56px;" value="5">
     <span class="input-group-addon"><div><div class="fa fa-sort-up inc2"></div></div><br>
     <div><div class="fa fa-sort-down dec2"></div></div></span>
    </div>
    </div>
    <div class="col-md-4 col-sm-4"></div>
    </div>
    </div>
    </div>
    <div style="padding-top: 30px;">

     <div class="form-group">
          <div>What other tools are you using with EdGenie to prepare for exam?</div>
          <div><input type="checkbox" name="c1">Youtube, blogs & articles</div>
          <div><input type="checkbox" name="c2">Books</div>
          <div><input type="checkbox" name="c3">Coaching classroom</div>
          <div><input type="checkbox" name="c4">Online practice products</div>
          <div style="padding-top: 10px;">Name other tools you use for prepration</div>
          <input type="text" class="form-control" name="tools" style="height: 40px; border: 1px solid #CCCCCC;">
          </div>
          </div>
          <div>
      <p>Mark the topics you think are your strength?</p>
    </div>
          <div style="padding-top: 30px;">
      <input type="submit" value="Continue to mathematics" class="btn btn-primary form-control" style="background-color: #006699; height: 40px;" id="qbtn">
      </div>
      </div>

    	</form>
    </div>
    </div>
    </div>

    <div class="col-md-4"></div>
    </div>

    <script src="{% static 'student/bootstrap/js/jquery.min.js' %}"></script>
  <script src="{% static 'student/bootstrap/js/bootstrap.js' %}"></script>
  <script src="{% static 'student/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'student/bootstrap/js/jquery-ui.js' %}"></script>
  <script src="{% static 'student/bootstrap/js/jquery-ui.min.js' %}"></script>
  <script src="{% static 'student/bootstrap/js/jquery.flip.js' %}"></script>
  <script src="{% static 'student/bootstrap/js/jquery.flip.min.js' %}"></script>
  <script src="{% static 'student/bootstrap/js/some.js' %}"></script>
  <script src="{% static 'student/bootstrap/js/custom.js' %}"></script>
  <script src="{% static 'student/bootstrap/js/bootstrap-datepicker.js' %}"></script>
  <script type="text/javascript">
  $(document).circleColor();
  $('.radiobtn').button();
  $(document).clickQuant();
  $("#inputDate").datepicker();

  $('.dropdown-toggle').dropdown();
  </script>
  </body>

project_at_v1_1/student/templates/student/student-d.html
<div class="form-group ques">

<script>
var t = '{{type}}';
var textstr = '{{s}}';
var divdata = [];
var noptions = parseInt('{{arr|length}}');
{% for i in arr %}
	divdata.push('{{i}}');
{% endfor %}
</script>

project_at_v1_1/student/templates/student/tutors.html
<div class="col-md-12"><h2>Tutors(231)</h2></div>
{% for i in "abcdefghijklmno" %}
<div class="col-md-12" style="padding-bottom: 15px;">
<div class="col-md-2" style="border: 1px solid gray; padding: 10px;"><img src="" class="img-responsive" alt="Responsive image" style="height: 151px;"></div>
<div class="col-md-10" style="border: 1px solid gray; padding: 14px;">
	<div><a href="{% url 'students:tutorprofiles' username='Josh1' %}">Josh Atlas</a></div>
	<div>San Francisco</div>
	<div style="font-size: 12px;"><b>720</b> SAT Score</div>
	<div style="font-size: 12px;"><b>12</b> students recommended me</div>
	<div style="padding-bottom: 16px; font-size: 13px;">Average tutor rating</div>
	<div><button class="btn btn-primary" id="message{{i}}">message</button></div>
</div>
</div>
<div class="modal fade" id="messagemodal{{i}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" style="padding: 0px;">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel" align="center">New Message</h4>
      </div>
      <div class="modal-body" id="messagebody{{i}}">
      <div class="col-md-12">
<div>To: Josh Atlas+{{i}}</div></div>
<div class="col-md-12" style="padding-bottom: 20px;">
<textarea cols="10" rows="6" placeholder="write your message..." class="form-control" id="textbody{{i}}"></textarea>
</div>
<div align="center">
<button class="btn btn-primary" id="send{{i}}">send message</button>
<button class="btn btn-primary" data-dismiss="modal">cancel</button>
</div>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% for i in 'abcdefghijklmno' %}
<script type="text/javascript">
	$('#message{{i}}').click(function(){
		$('#messagemodal{{i}}').modal();
	});

	$('#send{{i}}').click(function(){
    var mailbody = $('#textbody{{i}}').val();
    var a = '<div align="center"><img src="/static/student/images/ajax-loader.gif" />Sending Message...</div>';
    $(document).ajaxStart(function(){
    $('#messagebody{{i}}').append(a);
  });
    var j = $.get('/mailsent', {m: mailbody}).done(function(data){
      $('#messagebody{{i}}').html(data);
    }).fail(function(){
      alert("request failed");
    });
  });
</script>
{% endfor %}